---
name: Develop Frontend Portfolio Website

on:
  push:
    branches-ignore:
      - release
      - main
      - develop

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend Portfolio Website
    runs-on: ubuntu-latest
    steps:
      - run: echo 'event name is:' ${{ github.event_name }} 
      - run: echo 'event type is:' ${{ github.event.action }} 
      - name: "📥  checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🔍  Verify Changed Frontend Portfolio Website Files"
        uses: tj-actions/changed-files@v23.1
        id: changed-frontend-portfolio-website-files
        with:
          files: |
              frontend/portfolio-website/**/*
              frontend/living-style-guide/**/*.scss

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-frontend-portfolio-website-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: "🔄  Cache node_modules"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "🔧  Setup NodeJS 14.19.1"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: "📦  Install Frontend Portfolio Website Development dependencies"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        run: |
          bash scripts/frontend-portfolio-website-install.bash
          bash scripts/frontend-living-style-guide-install.bash
          bash scripts/frontend-js-component-library-install.bash
          bash scripts/assets-install.bash

      - name: "🔍  Lint Frontend Portfolio Website"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-portfolio-website-lint.bash

      - name: '🧪  Test Frontend JavaScript Component Library'
        if: steps.changed-frontend-static-website-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-js-component-library-test.bash

      - name: '🧪  Test Frontend Living Style Guide'
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-living-style-guide-test.bash

      - name: "🏗️  Build Frontend Portfolio Website"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          bash scripts/assets-process.bash
          bash scripts/frontend-portfolio-website-build.bash production