---
name: CD - Release
on:
    push:
        branches:
            - releases/*

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        env:
            NODE_VERSION: v24.14.0
            SITE_URL: https://paulalexserban.github.io/prj--personal-portfolio--v2
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: '🔄  Cache node_modules'
              uses: actions/cache@v5
              with:
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: '🔧 Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: '📦  Install CI dependencies'
              run: npm run install:ci

            - name: '🚀 Create Release'
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
